// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
		int n = Integer.parseInt(args[0]);
		double gtHalf = 0;
		double lteHalf = 0;

		for(int i=0; i<n; i++){
			double num = Math.random();
			if(num>0.5){ gtHalf++; }
			else { lteHalf++; }
		}

		System.out.println("> 0.5: "+(int) gtHalf+" times");
		System.out.println("<= 0.5: "+(int) lteHalf+" times");
		if(lteHalf!=0){
			System.out.println("Ratio: "+gtHalf/lteHalf);
		}


	}
}
